export const PAYROLL_ADJUSTMENT_TYPES = {
  BONUS: 'bonus',
  PENALTY: 'penalty',
  ADVANCE: 'advance',
  REDUCTION: 'reduction',
  ADJUSTMENT: 'adjustment',
  PAYMENT: 'payment',
}

export const PAYROLL_ADJUSTMENT_LABELS = {
  [PAYROLL_ADJUSTMENT_TYPES.BONUS]: 'Thưởng',
  [PAYROLL_ADJUSTMENT_TYPES.PENALTY]: 'Phạt',
  [PAYROLL_ADJUSTMENT_TYPES.ADVANCE]: 'Ứng lương',
  [PAYROLL_ADJUSTMENT_TYPES.REDUCTION]: 'Giảm lương',
  [PAYROLL_ADJUSTMENT_TYPES.ADJUSTMENT]: 'Điều chỉnh khác',
  [PAYROLL_ADJUSTMENT_TYPES.PAYMENT]: 'Thanh toán lương',
}

export const PAYROLL_WALLET_SOURCE = {
  MANUAL: 'manual',
  INVOICE: 'invoice',
  ATTENDANCE: 'attendance',
}

export const PAYROLL_DETAIL_CATEGORIES = {
  BASE: 'baseSalary',
  REVENUE: 'ticketRevenue',
  COMMISSION: 'commission',
  TIPS: 'tips',
  BONUS: 'bonus',
  REDUCTION: 'reduction',
  PENALTY: 'penalty',
  ADVANCE: 'advance',
  ADJUSTMENT: 'otherAdjustment',
  NET: 'netSalary',
}

export const PAYROLL_DETAIL_LABELS = {
  [PAYROLL_DETAIL_CATEGORIES.BASE]: 'Lương cơ bản',
  [PAYROLL_DETAIL_CATEGORIES.REVENUE]: 'Doanh thu tiền vé',
  [PAYROLL_DETAIL_CATEGORIES.COMMISSION]: 'Hoa hồng',
  [PAYROLL_DETAIL_CATEGORIES.TIPS]: 'Tips',
  [PAYROLL_DETAIL_CATEGORIES.BONUS]: 'Thưởng',
  [PAYROLL_DETAIL_CATEGORIES.REDUCTION]: 'Giảm lương',
  [PAYROLL_DETAIL_CATEGORIES.PENALTY]: 'Phạt',
  [PAYROLL_DETAIL_CATEGORIES.ADVANCE]: 'Ứng lương',
  [PAYROLL_DETAIL_CATEGORIES.ADJUSTMENT]: 'Điều chỉnh khác',
  [PAYROLL_DETAIL_CATEGORIES.NET]: 'Lương thực nhận',
}

export const MANUAL_ADJUSTMENT_OPTIONS = [
  PAYROLL_ADJUSTMENT_TYPES.BONUS,
  PAYROLL_ADJUSTMENT_TYPES.PENALTY,
  PAYROLL_ADJUSTMENT_TYPES.ADVANCE,
  PAYROLL_ADJUSTMENT_TYPES.REDUCTION,
  PAYROLL_ADJUSTMENT_TYPES.ADJUSTMENT,
]
